# coturn configuration for Mosaic local development
listening-port=3478
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=mosaicsecret
realm=localhost
min-port=49152
max-port=49160
log-file=stdout
verbose
user=mosaic:mosaicsecret
